### ISSUE TITLE
Conflict with USP - AIO

### ISSUE THREAD

**Issue by verybigman311** [BrettMayson/Arma-AttributesFastLoad#1]
The USP mod adds SO MANY ITEMS, such as things like ~1000 beard variants. This completely breaks the mod due to the cluttered items and makes attributes take ~20 seconds to load. However this only applies to the attribute menu of specific objects such as vehicles.

I think it has something to do with the vehicle inventory in editor needing to load each and every item from that cluttered mod.
Is there a way that vehicle inventories can be prevented from having to load items from USP specifically? Some sort of patch?

**Comment by BrettMayson** [comment]
This mod modifies the code made by BI to be much faster and more efficient, but it can't do magic. If there are an extremely large amount of items it will just take that long to load

**Comment by verybigman311** [comment]
how do i fix it doe?

**Comment by BrettMayson** [comment]
It's not broken, I'm sure if you launched without this mod it would be ridiculously slow. This mod helps, but it can't do magic

**Comment by verybigman311** [comment]
I meant fix my situation or something along those lines 

How can I delete some of the cluttered items from the USP files? In order to lighten the attributes load thingy. 

I tried removing some stuff from the PBO files using pbo manager but it did nothing.
